name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  RUNNER: PIPELINE
  PHP_VERSION: '7.4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Validate composer.json and composer.lock
        run: make lint-composer

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: make composer

      - name: Pack and upload the build
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: .

  test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site build
        uses: actions/download-artifact@v2
        with:
          name: website
          path: .

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Lint PHP files
        run: make lint-php

      - name: Check PHP styles
        run: make phpcs

      - name: Unit Tests
        run: make tests
